#!/usr/bin/env python3
"""
cocotb testbench for {{RTL_TOP}}
Generated by project template install script
"""

import cocotb
from cocotb.clock import Clock
from cocotb.triggers import Timer, RisingEdge, FallingEdge
from cocotb.result import TestSuccess, TestFailure


@cocotb.test()
async def test_reset(dut):
    """Test reset behavior"""
    dut._log.info("Starting reset test")
    
    # Create clock
    clock = Clock(dut.clk, 10, units="ns")
    cocotb.start_soon(clock.start())
    
    # Apply reset
    dut.rst_n.value = 0
    await Timer(100, units="ns")
    dut.rst_n.value = 1
    await Timer(100, units="ns")
    
    dut._log.info("Reset test completed")


@cocotb.test()
async def test_basic_operation(dut):
    """Test basic operation"""
    dut._log.info("Starting basic operation test")
    
    # Create clock
    clock = Clock(dut.clk, 10, units="ns")
    cocotb.start_soon(clock.start())
    
    # Release reset
    dut.rst_n.value = 0
    await RisingEdge(dut.clk)
    await RisingEdge(dut.clk)
    dut.rst_n.value = 1
    await RisingEdge(dut.clk)
    
    # TODO: Add specific test cases for {{RTL_TOP}}
    
    dut._log.info("Basic operation test completed")


@cocotb.test()
async def test_random_stimulus(dut):
    """Test with random stimulus"""
    import random
    
    dut._log.info("Starting random stimulus test")
    
    # Create clock
    clock = Clock(dut.clk, 10, units="ns")
    cocotb.start_soon(clock.start())
    
    # Release reset
    dut.rst_n.value = 0
    await RisingEdge(dut.clk)
    await RisingEdge(dut.clk)
    dut.rst_n.value = 1
    
    # Apply random stimulus
    for _ in range(100):
        await RisingEdge(dut.clk)
        # TODO: Add random input generation
    
    dut._log.info("Random stimulus test completed")
